### ISSUE TITLE
Convert this syntax theme into a duotone-dark color scheme

### ISSUE THREAD

**Issue by varemenos** [smlombardi/duotone-blue-dark#1]
simurai's duotone-dark-syntax will soon support schemes (for example [lime-orchid](https://github.com/simurai/duotone-dark-syntax/blob/sm-config/styles/schemes/lime-orchid.less)). Would you be interested into turning this syntax theme into a color scheme and put it in the duotone-dark project? This way, it will always be up to date with duotone-dark

**Comment by smlombardi** [comment]
sure.  I'd rather have one of them maintained than many.  

As I said, all I did was change the hue on 2 base colors, nothing more.

**Comment by varemenos** [comment]
It seems like the schemes feature was never merged in master due to technical difficulties so unfortunately this issue is no longer valid. If they ever manage to implement it, I will reopen the issue.

**Comment by thoragio** [comment]
@varemenos @smlombardi  Does [this other package](https://github.com/simurai/tone-syntax) look like it would accommodate the settings for duotone-blue-dark?
